### ISSUE TITLE
Result key to be end of period

### ISSUE THREAD

**Issue by waynerobinson** [ankane/groupdate#163]
Is it possible to get an option for the key to be the end of the period instead of the start?

**Comment by ankane** [comment]
Hey @waynerobinson, can you explain more about a use case for this?

**Comment by waynerobinson** [comment]
When talking about months or years, the values are actually the total at the end of the period anyway. If we show the whole date in results, then it seems like the total is for the start of the period.

The only reason you'd never really see this is if you're only presenting it as the _month_ or _year_.

**Comment by ankane** [comment]
The values are typically for the *range* rather than the start or end specifically (it's more clear when you think about something like average instead of count).

Since it should be easy enough to `map` the values afterward if needed, I don't see a strong reason for adding an option, but I appreciate the suggestion.
