### ISSUE TITLE
Group => 0

### ISSUE THREAD

**Issue by thekeenant** [ankane/groupdate#37]
I have "discussions" and would like to show statistics on discussion creation so I set out to get some charts working (Chartkick + groupdate). Going by the very first example on the readme, Discussion.group_by_day(:created_at).count should work I assume. Here's the results: http://pastie.org/9001756. The correct dates are shown, but the count is always 0 when it should be either 1 or 0 in this case. The issue is consistent with other tables as well. 
- Running Rails 4.0.2 and Ruby 1.9.3
- Using MySQL Database and time zones are working

Could be a bug, or maybe there's something simple that I'm missing. Thanks for any help in advance!

**Comment by naughtystyle** [comment]
To support `:local` a workaround would be to create a class method that overrides the default time zone in the Active Record model that's used for the analytics and just leave the configuration as `ActiveRecord::Base.default_timezone = :local`.

```ruby
class AnalyticsData < ActiveRecord::Base
  def self.default_timezone
    :utc
  end
end
```

**Comment by smit1625** [comment]
I was able to get around this by simply changing the value of `ActiveRecord::Base.default_timezone` just before I used Groupdate, then switching it back afterward.  I'm not sure if this workaround has any horrifying implications or anything, but since I was only using it to group by year, I'm not too concerned.  Anyway, here's basically what I did in the view where I was using Groupdate:

    <% ActiveRecord::Base.default_timezone = :utc %>
    <% @events.group_by_year(:doors_open_at).count.each do |year, count| %>
      <%# Do stuff in here... %>
    <% end %>
    <% ActiveRecord::Base.default_timezone = :local %>

**Comment by gwalshington** [comment]
For anyone using SQLite, the above workaround won't work :/ 'Time zones not supported for SQLite'
